# Generated by Django 4.2.16 on 2024-09-30 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("libro", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BoardsModel",
            new_name="Book",
        ),
    ]
