# Generated by Django 4.2.16 on 2024-10-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libro", "0002_rename_boardsmodel_book"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("modificado", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
