# Generated by Django 4.2.16 on 2024-10-01 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("libro", "0003_boardsmodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boardsmodel",
            options={"permissions": (("es_miembro_1", "Es miembro con prioridad 1"),)},
        ),
    ]
