# Generated by Django 4.2.16 on 2024-10-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("libro", "0004_alter_boardsmodel_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boardsmodel",
            options={
                "permissions": (
                    ("es_miembro_1", "Es miembro con prioridad 1"),
                    ("development", "Permiso como Desarrollador"),
                    ("scrum_master", "Permiso como Scrum Master"),
                    ("product_owner", "Permiso como Product Owner"),
                )
            },
        ),
    ]
