# Generated by Django 4.2.16 on 2024-10-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libro", "0006_boardsmodel_creado_boardsmodel_valor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardsmodel",
            name="creado",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
